- tailwind.config.js
Links were only be underlined in paragraphs but now they are in lists too
> Link styles for lists

- components/Footer.tsx
> fix twitter link

- components/Background.tsx
- pages/_app.tsx
- pages/index.tsx
- Better index page title on mobile
- Hide background on mobile
- Default theme is light (to test if it fixes the dark mode flash)
> Mobile improvments

- .gitignore
- lib/rss/index.ts
- package.json
- pages/index.tsx
- yarn.lock
I saw [this](https://canary.discord.com/channels/713503345364697088/973296219587747840/973332524568834058) in the feedback channel on Discord and started wondering why we don't have one?
> add rss feed

- hooks/useOGImage.ts
> encode title + author in url

- components/NotionImage.tsx
- components/RenderBlock.tsx
- lib/notion/index.ts
- pages/api/image.ts
Implementation of https://github.com/railwayapp/mono/pull/4478 to reload the Notion images on failure
> Reload images on error

- components/Categories.tsx
- components/Nav.tsx
- components/PostItem.tsx
- components/PostList.tsx
- components/Seo.tsx
- constants.ts
- layouts/PostPage.tsx
- lib/types.ts
- pages/[category].tsx
- pages/index.tsx
- tailwind.config.js
> Updated blog index page

- README.md
When I used the starter I was a little lost on the structure, until I found another post on the blog which listed our the structure. Thus I am adding the details to the Readme file itself.
> Updated read me with more instructions

- components/PostCategory.tsx
- lib/notion/index.ts
- colours for all categories
- fix blog sorting
> Fix blog sorting and category colours

- components/PostList.tsx
- lib/notion/index.ts
- pages/p/[slug].tsx
- pages/sitemap.xml/index.tsx
> cleanup + hide unpublished posts from rss feed

- pages/p/[slug].tsx
Title says it all. Added an additional filter.
> Fix unpublished posts showing up in Suggestion Box

- components/Link.tsx
- components/ListBlock.tsx
- components/NotionHeading.tsx
- components/NotionText.tsx
- lib/notion/index.ts
- lib/types.ts
- package.json
- pages/p/[slug].tsx
- yarn.lock
- render sub-lists
- fix heading anchor links
> Render sublists and fix heading anchor linking

- components/RenderBlock.tsx
- utils.ts
> Support YouTube embeds

- components/RenderBlock.tsx
> Support quote blocks

- next.config.js
> add notion image url

- lib/notion/index.ts
- package.json
> properly paginate databases + blocks

- components/RenderBlock.tsx
- lib/notion/index.ts
> Add support for rendering `column_list` and `column` components

- components/RenderBlock.tsx
Oops should have reviewed my own code. Type no longer used + bonus console logs
> Remove console log + useless type

- components/Code.tsx
Adds Python syntax highlighting to code blocks.
> Python syntax highlighting

- hooks/usePostHog.ts
- package.json
- pages/_app.tsx
- yarn.lock
Adds PostHog session tracking in accordance with our Privacy Policy and Terms of Service to the blog.
> Adds PostHog to Blog via Hook
